<dec f='include/c++/12/bits/functexcept.h' l='109' type='void std::__throw_future_error(int )'/>
<doc f='include/c++/12/bits/functexcept.h' l='107'>// Helpers for exception objects in &lt;future&gt;</doc>
<dec f='include/c++/12/future' l='118' type='void std::__throw_future_error(int )'/>
<use f='include/c++/12/future' l='419' u='c' c='_ZNSt13__future_base13_State_baseV213_M_set_resultESt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEEb'/>
<use f='include/c++/12/future' l='436' u='c' c='_ZNSt13__future_base13_State_baseV221_M_set_delayed_resultESt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEESt8weak_ptrIS0_E'/>
<use f='include/c++/12/future' l='466' u='c' c='_ZNSt13__future_base13_State_baseV221_M_set_retrieved_flagEv'/>
<use f='include/c++/12/future' l='564' u='c' c='_ZNSt13__future_base13_State_baseV28_S_checkERKSt10shared_ptrIT_E'/>
